import JSZip from "jszip";

export interface DistroBuildConfig {
  distroName: string;
  desktopEnvironment: string;
  selectedApps: string[];
  wallpaperUrls: string[];
  designDescription: string;
  themeStyle: string;
}

// Map our DE ids -> archiso package list for that DE
const DE_PACKAGES: Record<string, string[]> = {
  gnome: ["gnome", "gnome-extra", "gdm"],
  kde: ["plasma-meta", "kde-applications-meta", "sddm"],
  xfce: ["xfce4", "xfce4-goodies", "lightdm", "lightdm-gtk-greeter"],
  i3wm: ["i3-wm", "i3status", "i3lock", "dmenu", "lightdm", "lightdm-gtk-greeter"],
  cinnamon: ["cinnamon", "cinnamon-translations", "lightdm", "lightdm-gtk-greeter"],
};

// Map our app ids -> arch package names
const APP_PACKAGES: Record<string, string> = {
  firefox: "firefox",
  chromium: "chromium",
  brave: "brave-bin",
  vscode: "code",
  vim: "vim",
  git: "git",
  docker: "docker",
  nodejs: "nodejs npm",
  python3: "python python-pip",
  vlc: "vlc",
  gimp: "gimp",
  obs: "obs-studio",
  audacity: "audacity",
  ufw: "ufw",
  wireshark: "wireshark-qt",
  nmap: "nmap",
  keepassxc: "keepassxc",
  htop: "htop",
  neofetch: "neofetch",
  tmux: "tmux",
  curl: "curl",
};

const safeSlug = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "custom-distro";

function buildPackagesFile(cfg: DistroBuildConfig): string {
  const base = [
    "base", "base-devel", "linux", "linux-firmware",
    "networkmanager", "sudo", "nano", "bash-completion",
    "archiso", "syslinux",
  ];
  const de = DE_PACKAGES[cfg.desktopEnvironment] ?? DE_PACKAGES.xfce;
  const apps = cfg.selectedApps.flatMap((id) => (APP_PACKAGES[id] ?? "").split(/\s+/)).filter(Boolean);
  const all = Array.from(new Set([...base, ...de, ...apps])).sort();
  return all.join("\n") + "\n";
}

function buildProfileDef(cfg: DistroBuildConfig): string {
  const slug = safeSlug(cfg.distroName);
  return `iso_name="${slug}"
iso_label="${slug.toUpperCase().replace(/-/g, "_")}_$(date +%Y%m)"
iso_publisher="${cfg.distroName}"
iso_application="${cfg.distroName} Live/Install Image"
iso_version="$(date +%Y.%m.%d)"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux.mbr' 'bios.syslinux.eltorito' 'uefi-x64.systemd-boot.esp' 'uefi-x64.systemd-boot.eltorito')
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'xz' '-Xbcj' 'x86' '-b' '1M' '-Xdict-size' '1M')
file_permissions=(
  ["/etc/shadow"]="0:0:400"
  ["/root"]="0:0:750"
  ["/usr/local/bin/choose-mirror"]="0:0:755"
)
`;
}

function buildPacmanConf(): string {
  return `[options]
HoldPkg = pacman glibc
Architecture = auto
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
ParallelDownloads = 5

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
`;
}

function buildBuildScript(cfg: DistroBuildConfig): string {
  const slug = safeSlug(cfg.distroName);
  return `#!/usr/bin/env bash
# Build script for "${cfg.distroName}"
# Generated by Lovable Distro Builder
#
# REQUIREMENTS:
#   - Arch Linux host (or Arch in a VM/container) with root access
#   - Packages: archiso, squashfs-tools, libisoburn
#       sudo pacman -S archiso squashfs-tools libisoburn
#
# USAGE:
#   tar -xzf ${slug}-build.tar.gz   # (if you got this as a tar.gz)
#   cd ${slug}-build
#   sudo ./build.sh
#
# Output: ./out/${slug}-YYYY.MM.DD-x86_64.iso

set -euo pipefail

PROFILE_DIR="$(cd "$(dirname "$0")" && pwd)"
WORK_DIR="\${PROFILE_DIR}/work"
OUT_DIR="\${PROFILE_DIR}/out"

if [ "\$EUID" -ne 0 ]; then
  echo "ERROR: run as root (sudo ./build.sh)"
  exit 1
fi

if ! command -v mkarchiso >/dev/null 2>&1; then
  echo "ERROR: archiso is not installed. On Arch:"
  echo "  sudo pacman -S archiso squashfs-tools libisoburn"
  exit 1
fi

mkdir -p "\${OUT_DIR}"
rm -rf "\${WORK_DIR}"

echo "==> Building ISO for ${cfg.distroName}..."
mkarchiso -v -w "\${WORK_DIR}" -o "\${OUT_DIR}" "\${PROFILE_DIR}"

echo ""
echo "✓ Done! ISO is in: \${OUT_DIR}"
ls -lh "\${OUT_DIR}"
`;
}

function buildAirootfsCustomize(cfg: DistroBuildConfig): string {
  const services = ["NetworkManager.service"];
  if (["gnome"].includes(cfg.desktopEnvironment)) services.push("gdm.service");
  else if (cfg.desktopEnvironment === "kde") services.push("sddm.service");
  else services.push("lightdm.service");

  return `#!/usr/bin/env bash
set -e -u

# Enable services
${services.map((s) => `systemctl enable ${s}`).join("\n")}

# Set default target to graphical
systemctl set-default graphical.target

# Default theme hint
echo "${cfg.themeStyle}" > /etc/distro-theme

# Install wallpapers (if any were bundled)
if [ -d /usr/share/backgrounds/${safeSlug(cfg.distroName)} ]; then
  echo "Wallpapers installed at /usr/share/backgrounds/${safeSlug(cfg.distroName)}"
fi
`;
}

function buildOsRelease(cfg: DistroBuildConfig): string {
  const slug = safeSlug(cfg.distroName);
  return `NAME="${cfg.distroName}"
PRETTY_NAME="${cfg.distroName}"
ID=${slug}
ID_LIKE=arch
BUILD_ID=rolling
HOME_URL="https://lovable.dev"
`;
}

function buildReadme(cfg: DistroBuildConfig): string {
  return `# ${cfg.distroName} — Build Bundle

This bundle contains an **archiso** profile for building a custom Arch Linux–based
live/install ISO matching your configuration.

## What's inside

- \`build.sh\` — one-command build entrypoint (run with sudo on Arch Linux)
- \`profiledef.sh\` — archiso profile definition
- \`packages.x86_64\` — package list (base + ${cfg.desktopEnvironment} + your selected apps)
- \`pacman.conf\` — pacman config used during build
- \`airootfs/\` — files copied into the live system
- \`wallpapers/\` — your uploaded wallpapers (also bundled into the ISO)

## Build it

You need an **Arch Linux** machine (or VM/container) with root access:

\`\`\`bash
sudo pacman -S archiso squashfs-tools libisoburn
sudo ./build.sh
\`\`\`

The output ISO will appear in \`./out/\`. Flash it with \`dd\` or use Ventoy/Etcher.

## Configuration summary

- **Desktop environment:** ${cfg.desktopEnvironment}
- **Theme style:** ${cfg.themeStyle}
- **Apps:** ${cfg.selectedApps.join(", ") || "(none)"}
- **Wallpapers:** ${cfg.wallpaperUrls.length}
${cfg.designDescription ? `\n**Design notes:**\n> ${cfg.designDescription}\n` : ""}
---
Generated by Lovable Distro Builder.
`;
}

async function fetchAsBlob(url: string): Promise<Blob | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    return await res.blob();
  } catch {
    return null;
  }
}

export async function generateBuildBundle(cfg: DistroBuildConfig): Promise<Blob> {
  const slug = safeSlug(cfg.distroName);
  const zip = new JSZip();
  const root = zip.folder(`${slug}-build`)!;

  root.file("build.sh", buildBuildScript(cfg), { unixPermissions: 0o755 });
  root.file("profiledef.sh", buildProfileDef(cfg), { unixPermissions: 0o755 });
  root.file("packages.x86_64", buildPackagesFile(cfg));
  root.file("pacman.conf", buildPacmanConf());
  root.file("os-release", buildOsRelease(cfg));
  root.file("README.md", buildReadme(cfg));

  const airootfs = root.folder("airootfs")!;
  const customize = airootfs.folder("root")!;
  customize.file("customize_airootfs.sh", buildAirootfsCustomize(cfg), { unixPermissions: 0o755 });

  // os-release into the live system too
  const etc = airootfs.folder("etc")!;
  etc.file("os-release", buildOsRelease(cfg));

  // Wallpapers: download from signed URLs and bundle
  if (cfg.wallpaperUrls.length > 0) {
    const wpFolder = airootfs.folder(`usr/share/backgrounds/${slug}`)!;
    const localFolder = root.folder("wallpapers")!;
    let i = 0;
    for (const url of cfg.wallpaperUrls) {
      const blob = await fetchAsBlob(url);
      if (!blob) continue;
      // best-effort extension
      const extMatch = url.match(/\.(png|jpe?g|webp|gif|bmp)/i);
      const ext = (extMatch?.[1] ?? "jpg").toLowerCase();
      const name = `wallpaper-${++i}.${ext}`;
      const buf = await blob.arrayBuffer();
      wpFolder.file(name, buf);
      localFolder.file(name, buf);
    }
  }

  return await zip.generateAsync({ type: "blob", compression: "DEFLATE", compressionOptions: { level: 6 } });
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export const bundleFilename = (distroName: string) => `${safeSlug(distroName)}-build.zip`;
